/**
 * Image processing, against real files and a real worker.
 *
 * These use images generated by sharp rather than fixtures on disk: it
 * keeps the repository free of binary blobs, and it means a test can ask
 * for exactly the dimensions it wants to reason about.
 *
 * The case that matters most is the last one. Everything before it checks
 * that correct input produces correct output; the fake-image test checks
 * that *incorrect* input is caught — which is the whole reason content
 * validation exists on top of the declared MIME type.
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import request from 'supertest';
import sharp from 'sharp';
import { Worker, type Queue } from 'bullmq';
import type Redis from 'ioredis';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { LocalStorage } from '../src/storage.js';
import { FileRepository } from '../src/files/repository.js';
import { createQueue, QUEUE_NAME, type JobPayload } from '../src/jobs/queue.js';
import { runJobWithRetryPolicy } from '../src/jobs/processors.js';
import { resolveMimeType } from '../src/files/upload.js';
import { probeRedis, testRedis, queueRedis } from './helpers.js';

const available = await probeRedis();

const config = loadConfig({ NODE_ENV: 'test', LOG_LEVEL: 'fatal' });

let redis: Redis;
let qConn: Redis;
let wConn: Redis;
let queue: Queue<JobPayload>;
let worker: Worker<JobPayload> | null = null;
let storageRoot: string;

beforeAll(async () => {
  if (!available) return;
  redis = testRedis('images');
  qConn = queueRedis('images');
  wConn = queueRedis('images');
  storageRoot = await mkdtemp(join(tmpdir(), 'ff-image-test-'));
  queue = createQueue(qConn);

  const storage = new LocalStorage(storageRoot);
  const files = new FileRepository(redis);
  worker = new Worker<JobPayload>(
    QUEUE_NAME,
    (job) => runJobWithRetryPolicy(job, { storage, files }),
    { connection: wConn, concurrency: 2 },
  );
});

afterAll(async () => {
  if (!available) return;
  await worker?.close();
  await queue.close();
  await Promise.all([redis.quit(), qConn.quit(), wConn.quit()]);
  await rm(storageRoot, { recursive: true, force: true });
});

beforeEach(async () => {
  if (!available) return;
  await redis.flushdb();
});

function buildApp() {
  return createApp({
    config,
    redis,
    storage: new LocalStorage(storageRoot),
    files: new FileRepository(redis),
    queue,
  });
}

/** A solid-colour PNG of the requested size. */
async function makePng(width: number, height: number): Promise<Buffer> {
  return sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 40, g: 120, b: 200 },
    },
  })
    .png()
    .toBuffer();
}

async function uploadImage(
  app: ReturnType<typeof buildApp>,
  bytes: Buffer,
  filename = 'photo.png',
  contentType = 'image/png',
): Promise<string> {
  const response = await request(app)
    .post('/uploads')
    .attach('file', bytes, { filename, contentType });
  return response.body.id as string;
}

/** Queues an operation and waits for it to settle. */
async function runOperation(
  app: ReturnType<typeof buildApp>,
  fileId: string,
  operation: string,
  options: Record<string, unknown> = {},
  timeoutMs = 15_000,
) {
  const created = await request(app)
    .post('/jobs')
    .send({ fileId, operation, options });

  const deadline = Date.now() + timeoutMs;
  let last: Record<string, unknown> = {};

  while (Date.now() < deadline) {
    const response = await request(app).get(`/jobs/${created.body.id}`);
    last = response.body;
    if (last.state === 'failed') return last;
    // `!= null` catches both null and undefined. BullMQ marks a job
    // completed and writes its return value in separate steps, so there is
    // a window where the state says done but the result is still null —
    // narrow enough to never appear on a fast machine, wide enough to make
    // this flaky on a slow one.
    if (last.state === 'completed' && last.result != null) return last;
    await new Promise((resolve) => setTimeout(resolve, 150));
  }
  return last;
}

describe.skipIf(!available)('resizing', () => {
  it('scales an image down to the requested width', async () => {
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(1200, 800));

    const job = await runOperation(app, fileId, 'image.resize', { width: 400 });
    const details = (job.result as { details: Record<string, number> }).details;

    expect(job.state).toBe('completed');
    expect(details.width).toBe(400);
  });

  it('preserves the aspect ratio', async () => {
    // 1200x800 is 3:2, so a 400-wide result should be about 267 tall.
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(1200, 800));

    const job = await runOperation(app, fileId, 'image.resize', { width: 400 });
    const details = (job.result as { details: Record<string, number> }).details;

    expect(details.height).toBeGreaterThan(260);
    expect(details.height).toBeLessThan(275);
  });

  it('does not enlarge a smaller image', async () => {
    // Scaling up invents detail that was never there, so the default is
    // to leave a small image alone.
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(100, 100));

    const job = await runOperation(app, fileId, 'image.resize', { width: 800 });
    const details = (job.result as { details: Record<string, number> }).details;

    expect(details.width).toBe(100);
  });

  it('produces a smaller file than the source', async () => {
    const app = buildApp();
    const source = await makePng(1200, 800);
    const fileId = await uploadImage(app, source);

    const job = await runOperation(app, fileId, 'image.resize', { width: 300 });
    const details = (job.result as { details: Record<string, number> }).details;

    expect(details.bytes).toBeLessThan(source.length);
  });

  it('rejects a resize with no dimensions', async () => {
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(200, 200));

    const job = await runOperation(app, fileId, 'image.resize', {});

    expect(job.state).toBe('failed');
  });

  it('rejects an absurd requested size', async () => {
    // An unbounded resize is a denial-of-service waiting to happen.
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(200, 200));

    const job = await runOperation(app, fileId, 'image.resize', {
      width: 99_999,
    });

    expect(job.state).toBe('failed');
  });
});

describe.skipIf(!available)('format conversion', () => {
  it('converts PNG to WebP', async () => {
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(400, 300));

    const job = await runOperation(app, fileId, 'image.convert', {
      format: 'webp',
    });
    const details = (job.result as { details: Record<string, string> }).details;

    expect(job.state).toBe('completed');
    expect(details.format).toBe('webp');
  });

  it('rejects a format it cannot produce', async () => {
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(100, 100));

    const job = await runOperation(app, fileId, 'image.convert', {
      format: 'bmp',
    });

    expect(job.state).toBe('failed');
  });
});

describe.skipIf(!available)('thumbnails', () => {
  it('produces a square thumbnail of the requested size', async () => {
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(1000, 600));

    const job = await runOperation(app, fileId, 'image.thumbnail', {
      size: 128,
    });
    const details = (job.result as { details: Record<string, unknown> }).details;

    expect(job.state).toBe('completed');
    expect(details.size).toBe(128);
    expect(details.format).toBe('webp');
  });
});

describe.skipIf(!available)('downloading output', () => {
  it('serves a processed image that is really an image', async () => {
    const app = buildApp();
    const fileId = await uploadImage(app, await makePng(800, 600));

    const job = await runOperation(app, fileId, 'image.resize', { width: 200 });
    const key = (job.result as { outputs: string[] }).outputs[0];

    const response = await request(app).get(`/files/${key}`);

    expect(response.status).toBe(200);
    expect(response.headers['content-type']).toContain('image/');

    // Decode what came back: proof it is a usable image, not just bytes.
    const metadata = await sharp(response.body).metadata();
    expect(metadata.width).toBe(200);
  });

  it('404s for an unknown key', async () => {
    const app = buildApp();

    const response = await request(app).get('/files/outputs/nope.png');

    expect(response.status).toBe(404);
  });

  it('refuses a key that tries to escape storage', async () => {
    const app = buildApp();

    const response = await request(app).get('/files/../../etc/passwd');

    expect(response.status).toBe(404);
  });
});

describe.skipIf(!available)('content validation', () => {
  it('fails a file that claims to be an image but is not', async () => {
    // The declared MIME type is a claim by the caller; the bytes are the
    // truth. This is the check the upload filter cannot make.
    const app = buildApp();
    const fileId = await uploadImage(
      app,
      Buffer.from('this is definitely not a PNG'),
      'fake.png',
      'image/png',
    );

    const job = await runOperation(app, fileId, 'image.resize', { width: 100 });

    expect(job.state).toBe('failed');
    expect(String(job.error)).toContain('Not a readable image');
  });
});

describe('mime type resolution', () => {
  it('accepts a type that is already allowed', () => {
    expect(resolveMimeType('image/png', 'a.png')).toBe('image/png');
  });

  it('falls back to the extension for a generic type', () => {
    // curl sends application/octet-stream for anything it does not know,
    // which would otherwise reject a perfectly good CSV.
    expect(resolveMimeType('application/octet-stream', 'data.csv')).toBe(
      'text/csv',
    );
    expect(resolveMimeType('application/octet-stream', 'photo.JPG')).toBe(
      'image/jpeg',
    );
  });

  it('refuses a generic type with an extension we do not handle', () => {
    expect(resolveMimeType('application/octet-stream', 'thing.exe')).toBeNull();
  });

  it('refuses a specific type that is not allowed', () => {
    // A declared type we recognise as unwanted is not rescued by its name.
    expect(resolveMimeType('application/x-msdownload', 'thing.png')).toBeNull();
  });
});
