/**
 * What we know about an uploaded file, kept in Redis.
 *
 * The bytes live in storage; this records everything else — the original
 * filename, the declared type, the size, when it arrived. Two reasons the
 * two are separate: the storage key is generated by us and safe to use as
 * a path, while the original filename came from a user and is only ever
 * data; and a listing or a status check should not have to touch the
 * filesystem.
 *
 * Entries carry a TTL. Uploads here are transient by design — a file is
 * uploaded, processed, downloaded, and then it has served its purpose —
 * so metadata that outlives the file it describes is just clutter. The
 * expiry makes cleanup the default rather than a chore someone has to
 * remember.
 */

import type { Redis } from 'ioredis';
import { z } from 'zod';

/** How long an upload record survives without being refreshed. */
export const DEFAULT_TTL_SECONDS = 24 * 60 * 60; // 24 hours

const KEY_PREFIX = 'file:';

export const FileRecordSchema = z.object({
  id: z.string(),
  /** The key the bytes are stored under. Generated by us, never by a user. */
  storageKey: z.string(),
  /** What the user called it. Display only — never used as a path. */
  originalName: z.string(),
  mimeType: z.string(),
  size: z.number().int().nonnegative(),
  uploadedAt: z.string(),
});

export type FileRecord = z.infer<typeof FileRecordSchema>;

export class FileRepository {
  constructor(
    private readonly redis: Redis,
    private readonly ttlSeconds: number = DEFAULT_TTL_SECONDS,
  ) {}

  private keyFor(id: string): string {
    return `${KEY_PREFIX}${id}`;
  }

  async save(record: FileRecord): Promise<void> {
    await this.redis.set(
      this.keyFor(record.id),
      JSON.stringify(record),
      'EX',
      this.ttlSeconds,
    );
  }

  /**
   * Reads a record, or null if it is unknown or has expired.
   *
   * Parsing through the schema rather than casting means a corrupted or
   * outdated entry surfaces as "not found" instead of flowing onward as a
   * malformed object that breaks something further downstream.
   */
  async get(id: string): Promise<FileRecord | null> {
    const raw = await this.redis.get(this.keyFor(id));
    if (raw === null) {
      return null;
    }

    const parsed = FileRecordSchema.safeParse(JSON.parse(raw));
    return parsed.success ? parsed.data : null;
  }

  async delete(id: string): Promise<void> {
    await this.redis.del(this.keyFor(id));
  }

  async exists(id: string): Promise<boolean> {
    return (await this.redis.exists(this.keyFor(id))) === 1;
  }
}
